Integrating endpoints for User Profiles
AfriSplash-Remotely/Afrisplash-Frontend pull request #193
Opened 2024-02-26 11:50 UTC by VictorAJ01

2024-02-27 11:26 UTC, sammy-code98 requested changes

2024-02-28 15:53 UTC, VictorAJ01 commented on components/Dashboard/candidate/profile/index.tsx
> +    const { data } = useQuery(["recruiterProfile"], async () => {
Done

2024-02-28 15:54 UTC, VictorAJ01 commented on components/Dashboard/candidate/profile/index.tsx
> +                                    <p className="text-sm font-normal">{data?.role ?? "Backend Engineer"}</p>
Done

2024-02-29 02:45 UTC, sammy-code98 approved these changes

2024-03-06 20:47 UTC, chimdie requested changes

2024-03-06 20:47 UTC, chimdie commented on components/atoms/ToggleButton/index.tsx
>            className={`${styles.toggleCheckbox} border-2 border-gray-300 absolute block w-6 h-6 rounded-full bg-white appearance-none cursor-pointer`}
```suggestion
          className={`${styles.toggleCheckbox} border-2 border-gray-300 absolute block w-6 h-6 rounded-full bg-white appearance-none cursor-pointer aspect-square`}
```

2024-03-06 20:47 UTC, chimdie commented on components/atoms/ToggleButton/index.tsx
>            onChange={(e): React.ChangeEvent<HTMLInputElement> => onChange(e)}
can you create this function outside the template

2024-03-06 20:47 UTC, chimdie commented on components/Dashboard/recruiter/profile/index.tsx
>                                      className="w-14 h-14 rounded-full"
```suggestion
                                    className="w-14 h-14 rounded-full aspect-square"
```

2024-03-06 20:47 UTC, chimdie commented on package-lock.json
can you delete this file, use yarn to reinstall all dependencies

2024-03-07 10:54 UTC, VictorAJ01 commented on components/atoms/ToggleButton/index.tsx
>            className={`${styles.toggleCheckbox} border-2 border-gray-300 absolute block w-6 h-6 rounded-full bg-white appearance-none cursor-pointer`}
Done

2024-03-07 10:57 UTC, VictorAJ01 commented on components/Dashboard/recruiter/profile/index.tsx
>                                      className="w-14 h-14 rounded-full"
Done

2024-03-07 10:57 UTC, VictorAJ01 commented on package-lock.json
Okay

2024-03-07 11:06 UTC, VictorAJ01 commented on package-lock.json
Done

2024-03-07 12:33 UTC, chimdie approved these changes
@sammy-code98 LGTM

2024-03-07 12:35 UTC, chimdie commented
@VictorAJ01 Please fix the conflicts

2024-03-07 12:41 UTC, chimdie approved these changes
@copy-ninja1 @sammy-code98   Ready to be merged

2024-03-07 13:53 UTC, merged