feat: apply for  job save  a job, filter jobs
AfriSplash-Remotely/Afrisplash-Frontend pull request #200
Opened 2024-03-30 17:08 UTC by Daniekeys

### Background 

### Fixes 

### Change Summary

### Screeshots of the change

### Additional Notes

### Testing Procedure

### Related PRs or Issues 

#### PR Checklist

- [ ] `npm run lint` passes

2024-03-30 20:57 UTC, sammy-code98 requested changes

2024-03-30 20:57 UTC, sammy-code98 commented on api-endpoints/jobs/jobs.interface.ts
> +  salaryType: string | undefined | any;
why using undefined and any types here

2024-03-30 20:57 UTC, sammy-code98 commented on components/Dashboard/candidate/jobs/index.tsx
> +  { value: "London", label: "London" },
use the location array added for the recruiter create job

2024-03-30 20:57 UTC, sammy-code98 commented on components/jobCard/JobApplicationModal.tsx
> +                    salaryType === "range" ? `${salary?.min} - ${salary?.max}` : ` ${salary?.amount}`
please format this line properly

2024-03-30 20:57 UTC, sammy-code98 commented on components/jobCard/applyJobCard.tsx
> +    const handleNothing = () => {
remove this funcyion if it doesnt do anything

2024-04-01 08:41 UTC, chimdie approved these changes
@sammy-code98 @copy-ninja1 @Daniekeys  LGTM

2024-04-02 01:39 UTC, Daniekeys commented on api-endpoints/jobs/jobs.interface.ts
> +  salaryType: string | undefined | any;
fixed

2024-04-02 01:40 UTC, Daniekeys commented on components/jobCard/JobApplicationModal.tsx
> +                    salaryType === "range" ? `${salary?.min} - ${salary?.max}` : ` ${salary?.amount}`
done

2024-04-02 11:00 UTC, sammy-code98 approved these changes

2024-04-02 11:01 UTC, merged