Integrated List of Candidates Endpoint
AfriSplash-Remotely/Afrisplash-Frontend pull request #207
Opened 2024-04-18 21:01 UTC by VictorAJ01

-This PR implements integration of get_users_candidates endpoint and displays user data on the landing page

2024-04-19 04:15 UTC, sammy-code98 requested changes

2024-04-19 04:15 UTC, sammy-code98 commented on components/HomePageComponents/Talents.tsx
Great work chief

- please remove the second grid with the mentorsCard with static data in it.
- position the card with the text 'Become a top talent' as seen on the Figma (image below) and link to the sign-up page
![Screenshot from 2024-04-19 05-14-32](https://github.com/AfriSplash-Remotely/Afrisplash-Frontend/assets/46542941/5971168b-d81f-45e8-85ef-9682435d564d)

2024-04-19 10:20 UTC, Daniekeys approved these changes

2024-04-23 10:22 UTC, sammy-code98 approved these changes

2024-04-23 10:23 UTC, merged