fixing pr issue
AfriSplash-Remotely/Afrisplash-Frontend pull request #217
Opened 2024-06-03 21:36 UTC by sammy-code98

### Background 

### Fixes 

### Change Summary

### Screeshots of the change

### Additional Notes

### Testing Procedure

### Related PRs or Issues 

#### PR Checklist

- [ ] `npm run lint` passes

2024-06-04 20:23 UTC, sammy-code98 commented on assets/admin_icons/logout.svg
icons here are all displayed via an image tag

2024-06-04 21:37 UTC, sammy-code98 commented
> 1. This branch says `fix/logout`, but does a whole lot than just logout. Please let's stick to the tasks* to avoid overwhelming reviewers with too much files to go through.
> 2. I tried to login but I wasn't able to as I keep getting `401` which means my token does not get saved at all or something else I barely tried looking through.
> 3. There were a couple of `side effects` which were supposed to run once but were changed in this PR, can we go over them again to avoid unhandled effects running in
>    the _background_.
> 
> <img alt="Screenshot 2024-06-04 at 1 18 30 PM" width="856" src="https://private-user-images.githubusercontent.com/47675587/336445419-4f3536a3-c69f-4b48-9f46-52dcb7d69c78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1MzA5NTYsIm5iZiI6MTcxNzUzMDY1NiwicGF0aCI6Ii80NzY3NTU4Ny8zMzY0NDU0MTktNGYzNTM2YTMtYzY5Zi00YjQ4LTlmNDYtNTJkY2I3ZDY5Yzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDE5NTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOGVmOWZhNDEwMGNjMzljZDY4MzNlNTMzYjU2MmU4MjM4Y2E0NDNmOTU2Nzc5MWU3Y2Y0MzNiYzkyMDRlMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZzVatOR35lRDo6E0d69UxfBRPAAgqCqWYQ9mXOzAOyA">

- Sincere apologies for overloading a single pr with many file changes, had a few conflicts on my end that resulted in that. will do better in the future.
-  the thing with the side effects was a huge mistake on my end, thanks for pointing them out. will fix asap
- will get other issues raised along side

2024-06-05 15:29 UTC, chimdie requested changes

2024-06-05 15:29 UTC, chimdie commented on components/molecules/LogOutModal/index.tsx
Add the mobile functionality for the logout

2024-06-05 15:29 UTC, chimdie commented on components/molecules/LogOutModal/index.tsx
> +              "bg-[#0D5520] text-sm text-[white] px-12 py-2 rounded-lg w-1/2  md:w-auto"
Remove arbitrary value

2024-06-06 19:24 UTC, chimdie approved these changes
LGTM

2024-06-06 19:26 UTC, merged