New recruiter fix
AfriSplash-Remotely/Afrisplash-Frontend pull request #219
Opened 2024-06-20 17:46 UTC by Daniekeys

### Background 

Create job and create company were not working

### Fixes 

fixed the create company and create job feature and made them stable

### Change Summary

### Screeshots of the change

### Additional Notes

### Testing Procedure

### Related PRs or Issues 

#### PR Checklist

- [ ] `npm run lint` passes

2024-06-24 10:36 UTC, sammy-code98 commented on api-endpoints/company/company.api.ts
> +import { setApiHeaders } from "@/constants/setApiHeaders";
remove unused imports.

2024-06-24 10:37 UTC, sammy-code98 commented on api-endpoints/company/company.api.ts
> +export const fetchAllCompanies = async (): Promise<singleCompanyResp[]> => {
remove `[]` symbol on return type

2024-06-24 11:08 UTC, sammy-code98 requested changes

2024-07-09 18:42 UTC, Daniekeys commented
@sammy-code98 i have fixed all stuffs and also pulled from main

2024-07-11 16:49 UTC, sammy-code98 approved these changes

2024-07-11 16:49 UTC, merged