added two email verification pages with components
AfriSplash-Remotely/Afrisplash-Frontend pull request #61
Opened 2022-11-01 09:22 UTC by shagariboy

I worked on two pages:

- verify email/sign-up page
- after verification/go to login page

2022-11-02 12:05 UTC, copy-ninja1 requested changes

2022-11-02 12:05 UTC, copy-ninja1 commented on components/EmailVerified/EmailVerified.tsx
> +class EmailVerified extends Component {
let's stick to hooks instead

2022-11-05 08:45 UTC, shagariboy commented on styles/Verify-email.module.scss
> +
updated to Tailwind css

2022-11-05 08:45 UTC, shagariboy commented on components/EmailVerified/EmailVerified.tsx
> +class EmailVerified extends Component {
Made updates.

2022-11-05 15:07 UTC, merged

2022-11-06 10:05 UTC, shagariboy commented
I would like to remove the "styles/Verify-email.module.scss" file. It has a lot of bugs and is not useful anymore.